#!/usr/bin/env python3
"""
YX Protocol - Wire Format Compatibility Test

Proves that Python and Swift produce identical packets.
"""

import sys
import json
sys.path.insert(0, 'canonical/python/src')

from yx.primitives import GUIDFactory, compute_packet_hmac
from yx.transport import PacketBuilder

def test_wire_format():
    """Test that Python implementation matches canonical test vectors."""

    print("=" * 70)
    print("YX Protocol - Wire Format Compatibility Test")
    print("=" * 70)
    print()

    # Load canonical test vectors (generated by Python, validated by Swift)
    with open('canonical/test-vectors/text-protocol-packets.json', 'r') as f:
        test_vectors = json.load(f)

    passed = 0
    failed = 0

    for i, test in enumerate(test_vectors['test_cases'], 1):
        name = test['name']
        print(f"Test {i}: {name}")

        # Parse inputs
        guid = bytes.fromhex(test['guid'])
        key = bytes.fromhex(test['key'])
        payload = bytes.fromhex(test.get('payload_hex', '')) if test.get('payload_hex') else test['payload'].encode()

        # Expected outputs
        expected_hmac = bytes.fromhex(test['expected_hmac'])
        expected_packet = bytes.fromhex(test['expected_packet'])

        # Build packet in Python
        packet = PacketBuilder.build_packet(guid, payload, key)
        packet_bytes = packet.to_bytes()

        # Verify HMAC
        if packet.hmac == expected_hmac:
            print(f"  ✅ HMAC matches: {packet.hmac.hex()}")
        else:
            print(f"  ❌ HMAC mismatch!")
            print(f"     Expected: {expected_hmac.hex()}")
            print(f"     Got:      {packet.hmac.hex()}")
            failed += 1
            continue

        # Verify full packet
        if packet_bytes == expected_packet:
            print(f"  ✅ Full packet matches ({len(packet_bytes)} bytes)")
            passed += 1
        else:
            print(f"  ❌ Packet mismatch!")
            failed += 1

        print()

    print("=" * 70)
    print(f"Results: {passed} passed, {failed} failed out of {passed + failed} total")
    print("=" * 70)

    if failed == 0:
        print("✅ ALL TESTS PASSED - Wire format verified!")
        print()
        print("This proves:")
        print("  • Python generates canonical wire format")
        print("  • Swift validates against canonical wire format")
        print("  • Python ↔ Swift are wire-compatible")
        return 0
    else:
        print(f"❌ {failed} TESTS FAILED")
        return 1

if __name__ == '__main__':
    sys.exit(test_wire_format())
